replicaCount: 1

image:
  repository: 320662462741.dkr.ecr.us-west-2.amazonaws.com/finance-app
  pullPolicy: IfNotPresent
  tag: v0.0.1

deployment:
  containerPort: 3000

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000
  livenessProbePath: /health-check
  readinessProbePath: /health-check

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80